# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master


stages:
- stage: Tests
  jobs:

# Needed special checkout due the 'newline' tests
# https://blog-bertrand-thomas.devpro.fr/2021/05/26/azure-build-pipelines-protip-customize-git-checkout/
  - job: unittest
    pool:
      vmImage: 'windows-2019'
    displayName: 'unittest'
    steps:
    - script: "git config --global core.autocrlf false"
      displayName: "Configure Git"
    - checkout: self
      displayName: "Clone repository"
    - script: |
        exec_python_unittests_with_install.bat

  - job: pylint
    pool:
      vmImage: 'windows-2019'
    displayName: 'pylint'
    steps:
    - script: |
        exec_pylint_with_install.bat
