# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: gcc:6.1

# Help:
# https://confluence.atlassian.com/bitbucket/python-with-bitbucket-pipelines-873891271.html

# Validator:
# https://bitbucket-pipelines.prod.public.atl-paas.net/validator

# This is a Python test pipeline for SourceCodeChecker

image: python:3.7.2
pipelines:
  default:
    - step:
        script:
          - echo 'Start pipeline'
          
          # Print the Linux version.
          - uname -a
          
          - python --version

          # TODO: Review
          #- cd $BITBUCKET_CLONE_DIR
          - echo 'List actual directory'
          - pwd
          # Win: cd
          - ls

          - pip install -r requirements.txt
          
          #- python -m unittest discover tests/
          - python -m unittest FileAnalysis_UnitTest.py
          
          #- python -m pylint SourceCodeChecker.py --rcfile=pylintrc
          # https://docs.pylint.org/en/1.6.0/run.html
          # 1 - fatal, 2 - error, ..., 32 - usage
          - python -m pylint SourceCodeChecker.py --rcfile=pylintrc
          - PYLINT_EXIT_CODE=$?
            if [ $PYLINT_EXIT_CODE == 1 ] || [ $PYLINT_EXIT_CODE == 2 ] || [ $PYLINT_EXIT_CODE == 32 ]
            then
              echo 'Pylint exited with important error code'
              echo $PYLINT_EXIT_CODE
              exit 1
            else
              echo 'Pylint exited with ok / small error code'
              echo $PYLINT_EXIT_CODE
              exit 0
            fi
